models/blog.py
import time
from models import Model

# 针对我们的数据 comment
# 我们要做 4 件事情
"""
C create 创建数据
R read 读取数据
U update 更新数据
D delete 删除数据

Comment.new() 来创建一个 todo
"""


class Blog(Model):
    @classmethod
    def new(cls, form):
        """
        创建并保存一个 todo 并且返回它
        Todo.new({'title': '吃饭'})
        :param form: 一个字典 包含了 todo 的数据
        :return: 创建的 todo 实例
        """
        # 下面一行相当于 t = Todo(form)
        t = cls(form)
        t.save()
        return t

    def __init__(self, form):
        self.id = None
        self.title = form.get('title', '')
        self.content = form.get('content', '')
        self.author = form.get('author', '')
        self.create_time = int(time.time())


class BlogComment(Model):
    @classmethod
    def new(cls, form):
        """
        创建并保存一个 todo 并且返回它
        Todo.new({'title': '吃饭'})
        :param form: 一个字典 包含了 todo 的数据
        :return: 创建的 todo 实例
        """
        # 下面一行相当于 t = Todo(form)
        t = cls(form)
        t.save()
        return t

    def __init__(self, form):
        self.id = None
        self.content = form.get('content', '')
        self.author = form.get('author', '')
        self.blog_id = int(form.get('blog_id', 0))
        self.create_time = int(time.time())

models/comment.py
import time
from models import Model

# 针对我们的数据 comment
# 我们要做 4 件事情
"""
C create 创建数据
R read 读取数据
U update 更新数据
D delete 删除数据

Comment.new() 来创建一个 todo
"""


class Comment(Model):
    @classmethod
    def new(cls, form):
        t = cls(form)
        t.save()
        return t

    def __init__(self, form):
        self.id = None
        self.author = form.get("author", "")
        self.content = form.get("content", "")
        self.create_time = int(time.time())

routes/blog.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)
# 一次性引入多个 flask 里面的名字
# 注意最后一个后面也应该加上逗号
# 这样的好处是方便和一致性

from models.blog import (
    Blog,
    BlogComment,
)
from utils import log

# 创建一个 蓝图对象 并且路由定义在蓝图对象中
# 然后在 flask 主代码中「注册蓝图」来使用
# 第一个参数是蓝图的名字, 以后会有用(add函数里面就用到了)
# 第二个参数是套路
main = Blueprint('blog', __name__)

'''
1. 拆分有哪些页面
    1.1
    发博客 link 点进去以后呢进入发博客的页面
    1.2
    具体的博客，博客的标题。 可以被点击
    2.1
    博客正文， 作者，title, 时间，内容
    2.2
    发表评论的窗口，发表的评论，都是针对这个博客的
    2.3
    显示所有评论的地方，这个里面会有评论
    3.1 创建blog的页面

2. 组织那些数据，把数据的操作实现
Blog数据
1. id int
2. author
3. content
4. create_time

Blog的方法有哪些
1. new出来一个blog
2. 根据blog id拿到一个blog

BlogComment
1. id
2. author
3. comment
4. create_time
5. blog_id 也应该被索引

BlogComment操作
1. new
2. blog_id find

3. 逻辑 产品经理
    3.1 点创建blog 调到blog/new这个页面，去创建blog
    3.2 创建完毕，回到index
    3.3 点击某一个blog，进入blog的详细页
    3.4 在详情页，提交一条评论，跳转回来，显示评论
4. 开始实现代码
5. 剩下的部分一点点补全
6. 美化页面 视觉
7. 交互细节 交互
'''

@main.route("/")
def index():
    all_blog = Blog.all()
    return render_template("blog_index.html", blogs=all_blog)


@main.route("/add", methods=["POST"])
def add():
    form = request.form
    Blog.new(form)
    return redirect(url_for('.index'))


@main.route("/new", methods=["GET"])
def new():
    return render_template("blog_new.html")


#/blog/1
@main.route("/<int:blog_id>", methods=["GET"])
def view(blog_id):
    comments = BlogComment.find_all(blog_id=blog_id)
    blog = Blog.find(blog_id)
    return render_template("blog_view.html", blog=blog, comments = comments)


@main.route("/comment/new", methods=["POST"])
def comment():
    form = request.form
    BlogComment.new(form)
    return redirect(url_for('.view', blog_id=form.get("blog_id")))

# 传统  ： 传递回来一个页面
# 现代的方法呢： 是做成服务 访问一个网址，返回了json
# 1. 不同服务，可以用不用的语言
# 2. 拆分服务 业务里面 有一些部分很耗费性能，有一些部分不怎么耗费性能
# 在传统做法里面 n个app 对应不同的用户，让他访问不同的app
# 每个服务独立，复制的单位，是以服务为基础的 微服务，SOA,面向服务的架构

routes/comment.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)
# 一次性引入多个 flask 里面的名字
# 注意最后一个后面也应该加上逗号
# 这样的好处是方便和一致性

from models.comment import Comment
from utils import log

# 创建一个 蓝图对象 并且路由定义在蓝图对象中
# 然后在 flask 主代码中「注册蓝图」来使用
# 第一个参数是蓝图的名字, 以后会有用(add函数里面就用到了)
# 第二个参数是套路
main = Blueprint('comment', __name__)

'''
1. 拆分有哪些页面 一个页面就可以了，
---author---content----button---

-- comment---
-- comment---
。。。。。

2. 组织那些数据，把数据的操作实现
comment 数据结构
1. id
2. author String
3. content String
4. time int

comment 的数据上的方法
1. 新建评论
2. 所有的评论

数据结构 + 数据方法 类

3. 逻辑 产品经理
    3.1 add时候增加一个评论，然后跳转回到主页，在主页显示所有的评论
4. 开始实现代码，部分对，部分todo 开发工程师 测试工程师
5. 剩下的部分一点点补全
6. 美化页面 视觉
7. 交互细节 交互
'''

'''
1. tcp byte 数据流
2. http 严格要求了， request response // 发送给web framework什么？
    in： 已经parse过的request
    out: response writer
2.* 对于web framework 我看起来像是一个http server
    对于http server，我看起来像是一个web framework

    1. session sessionmiddlewareinterface
    2. cache memcached
3. web framework, flask
    3.1 M mongo redis mysql
    3.2 V jinja2
    3.3 C route
4. application
'''


@main.route('/')
def index():
    comments = Comment.all()
    return render_template('comment_new.html', comments=comments)


@main.route('/add', methods=['POST'])
def add():
    t = Comment.new(request.form)
    #t.save()
    return redirect(url_for('.index'))

routes/todo.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)
# 一次性引入多个 flask 里面的名字
# 注意最后一个后面也应该加上逗号
# 这样的好处是方便和一致性

from models.todo import Todo
from utils import log

# 创建一个 蓝图对象 并且路由定义在蓝图对象中
# 然后在 flask 主代码中「注册蓝图」来使用
# 第一个参数是蓝图的名字, 以后会有用(add函数里面就用到了)
# 第二个参数是套路
main = Blueprint('todo', __name__)


@main.route('/')
def index():
    # 查找所有的 todo 并返回
    todo_list = Todo.all()
    return render_template('todo_index.html', todos=todo_list)


# /todo/add only post
@main.route('/add', methods=['POST', 'GET'])
def add():
    if request.method == 'GET':
        return redirect(url_for('todo.index'))
    # request local
    # post form request.form()
    # get request.args
    form = request.form
    t = Todo.new(form)
    t.save()
    # 蓝图中的 url_for 需要加上蓝图的名字，这里是 todo

    # todo.index blueprint
    # todo.index
    # /todo/
    return redirect(url_for('todo.index'))


# 动态路由
@main.route('/delete/<int:todo_id>/')
def delete(todo_id):
    """
    <int:todo_id> 的方式可以匹配一个 int 类型
    int 指定了它的类型，省略的话参数中的 todo_id 就是 str 类型

    这个概念叫做 动态路由
    意思是这个路由函数可以匹配一系列不同的路由

    动态路由是现在流行的路由设计方案
    """
    # 通过 id 删除 todo
    t = Todo.delete(todo_id)
    log("deleted todo id", todo_id)
    # 引用蓝图内部的路由函数的时候，可以省略名字只用 .
    # 因为我们就在 todo 这个蓝图里面, 所以可以省略 todo
    # return redirect(url_for('todo.index'))
    return redirect(url_for('.index'))

templates/blog_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>博客主页</title>
</head>
<body>
<a href={{ url_for(".new") }}>新建博客</a>
<div>
    {% for b in blogs %}
        <div>
        <a href= {{ url_for(".view", blog_id=b.id) }}>
        {{ b.title }} @ {{ b.create_time }} by {{ b.author }}
        </a>
        </div>
    {% endfor %}
</div>

</body>
</html>

templates/blog_new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>发表新博文</title>
</head>
<body>
<form method="POST" action={{ url_for(".add") }}>
    <input type="text" name="author" placeholder="author">
    <input type="text" name="title" placeholder="title">
    <br>
    <textarea name = "content" placeholder="content">
    </textarea>
    <br>
    <button type="submit">发布</button>
</form>

</body>
</html>

templates/blog_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ blog.title }}</title>
</head>
<h1>{{ blog.title }}</h1>
<h3>{{ blog.author }}</h3>
<p>{{ blog.content }}</p>

<form method="post" action="comment/new">
    <input type="text" name="author" placeholder="author">
    <input type="text" name="content" placeholder="content">
    <input type="hidden" name="blog_id" value={{ blog.id }}>
    <button type="submit">提交评论</button>
</form>

<div>
    {% for c in comments %}
        <div>{{ c.content }} @ {{ c.author }}</div>
    {% endfor %}
</div>
<body>

</body>
</html>

templates/comment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="//cdn.bootcss.com/bootstrap/4.0.0-alpha.6/css/bootstrap.css" rel="stylesheet">
</head>
<body>
<form method="post" action="/comment/add">
    <input class="form-control" type="text" name="content" placeholder="comment">
    <input class="form-control" type="text" name="author" placeholder="author">
    <button class="btn btn-default" type="submit">提交留言</button>
</form>

<div>
    {% for c in comments %}
    <div class="bg-success">
        {{ c.content }} for {{ c.author }} @ {{ c.create_time }}
    </div>
    {% endfor %}
</div>

</body>
</html>

templates/comment_new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="//cdn.bootcss.com/bootstrap/4.0.0-alpha.6/css/bootstrap.css" rel="stylesheet">
</head>
<body>
<form method="post" action={{ url_for(".add") }}>
        <input class="form-control" type="text" name="author" placeholder="author">
        <input class="form-control" type="text" name="content" placeholder="content">
        <button class="btn btn-success" type="submit">提交</button>
</form>
{% for c in comments %}
    <div class="bg-success">{{ c.content }} from {{ c.author }} @ {{ c.create_time }}</div>
{% endfor %}
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>主页</title>
</head>
<body>
    <h1>{{ user }}</h1>
    <h2>
        <a href="{{ url_for('.profile') }}">个人资料页面</a>
    </h2>
    <form method="post" action="{{ url_for('.register') }}">
        <input name="username">
        <br>
        <input name="password">
        <br>
        <button type="submit">注册</button>
    </form>
    <form method="post" action="{{ url_for('.login') }}">
        <input name="username">
        <br>
        <input name="password">
        <br>
        <button type="submit">登录</button>
    </form>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="POST" action={{ url_for(".login") }}>
    <input type="text" name="user_name" placeholder="user_name">
    <button type="submit">提交</button>
</form>
</body>
</html>

templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>profile</title>
</head>
<body>
    <h1>用户资料页面</h1>
    <div>
        {{ user.id }}
    </div>
    <div>
        {{ user.name }}
    </div>
    <div>
        {{ user.password }}
    </div>
</body>
</html>

templates/session.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>hello {{ author }}</p>
<br>
<form method = "post" action= {{ url_for(".logout") }}>
    <button type="submit">退出</button>
</form>

</body>
</html>

templates/session_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p> hello {{ username }}!</p>
<form method="get" action={{ url_for(".log_out") }}>
    <button type="submit">退出登录</button>
</form>
</body>
</html>

templates/session_index2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<form method="post" action={{ url_for(".login") }}>
    <input type="text" name="author" placeholder="author">
    <button type="submit">提交</button>
</form>

</body>
</html>

templates/todo_index.html
<html>
<head>
    <title>Todo</title>
    <!-- 静态文件放在 /static 文件夹中 -->
    <!-- 引用路径是 /static/... -->
    <link rel="stylesheet" href="/static/css/pure-min.css">
    <style type="text/css">
    .todo-table {
        margin: 0 auto;
    }
    .center {
        text-align: center;
    }
    </style>
</head>

<body>
    <div class="center">
        <h1>Todo</h1>
        <!-- 注意这里 的 url_for 也是需要加上蓝图名字前缀的 -->
        <!-- action /todo/add-->
        <form action={{ url_for("todo.add") }} method="post">
            <input type="text" placeholder="Add Todo" name="title">
            <input class="pure-button pure-button-primary" type="submit" value="Add">
        </form>
    </div>

    <table class="todo-table pure-table pure-table-horizontal pure-table-striped">
        <thead>
            <tr>
                <th>#</th>
                <th>Title</th>
                <th>Time</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
        {% for t in todos %}
            <tr>
                <td>{{ t.id }}</td>
                <td>{{ t.title }}</td>
                <td>{{ t.time() }}</td>
                <!-- url_for 可以传递参数，先匹配动态路由，如果动态路由匹配失败则变成 query 参数 -->
                <td><a href={{ url_for('.delete', todo_id=t.id) }}>delete</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</body>
</html>